services:
  redis:
    image: redis:7-alpine
    command: ["redis-server","--appendonly","no"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    image: wschat:latest

    environment:
      REDIS_URI: redis://redis:6379
      JAVA_OPTS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
